name: flutter_module
description: A new Flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^9.2.0
  freezed_annotation: ^2.0.3
  uuid: ^3.0.6
  flutter_bloc: ^8.0.1
  auto_route: ^4.0.1
  get_it: ^7.2.0
  meta: ^1.1.8
  injectable: ^1.5.3
  json_annotation: ^4.5.0
  provider: ^6.0.3
  flutter_hooks: ^0.18.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  freezed: ^2.0.3+1
  auto_route_generator: ^4.0.0
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0


flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.welpup.flutter_module
    iosBundleIdentifier: com.welpup.flutterModule
